CREATE TABLE tb_doc (
  `seq` INT NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `doc_nm` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '문서명',
  `doc_url` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '문서 주소',
  `reg_dt` DATETIME NOT NULL DEFAULT '2022-01-01 00:00:00' COMMENT '등록일',
  `upd_dt` DATETIME NOT NULL DEFAULT '2022-01-01 00:00:00' COMMENT '수정일',
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;