CREATE TABLE tb_self (
  `seq` INT NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `mi01` FLOAT NOT NULL DEFAULT 0 COMMENT 'mi01',
  `mi05` FLOAT NOT NULL DEFAULT 0 COMMENT 'mi05',
  `mi15` FLOAT NOT NULL DEFAULT 0 COMMENT 'mi15',
  `used_mem` FLOAT NOT NULL DEFAULT 0 COMMENT 'used mem',
  `used_disk` FLOAT NOT NULL DEFAULT 0 COMMENT 'used disk',
  `reg_dt` DATETIME NOT NULL DEFAULT NOW() COMMENT '등록일',
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;