CREATE TABLE tb_sheet (
  `seq` INT NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `sheet_nm` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '문서명',
  `sheet_url` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '문서 주소',
  `reg_dt` DATETIME NOT NULL DEFAULT NOW() COMMENT '등록일',
  `upd_dt` DATETIME NOT NULL DEFAULT NOW() COMMENT '수정일',
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;