CREATE TABLE  tb_user (
  `seq` INT NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `user_nm` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '유저명',
  `user_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '유저 ID',
  `user_pw` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '비밀번호',
  `is_admin` VARCHAR(4) NOT NULL DEFAULT '' COMMENT '관리자 여부',
  `login_dt` DATETIME NOT NULL DEFAULT NOW() COMMENT '마지막 로그인',
  `reg_dt` DATETIME NOT NULL DEFAULT NOW() COMMENT '등록일',
  `upd_dt` DATETIME NOT NULL DEFAULT NOW() COMMENT '수정일',
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;